spring:
  messages:
    basename: lang.messages
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: URLDataBase
    username: NAME
    password: PASS
sites:
  url:
    - http://www.playback.ru
    - https://www.lutherancathedral.ru
    - https://dombulgakova.ru
  name:
    - PlayBack
    - Lutheranca
    - Dombulgakove
  user-agent: Mozilla/5.0 (Windows; U; WindowsNT 5.1; en-US; rv1.8.1.6) Gecko/20070725 Firefox/2.0.0.6
